apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolume2
  namespace: default
spec:
  capacity:
    storage: 50Gi
  csi:
    driver: blob.csi.azure.com
    volumeHandle: bpstracc_containertest
    volumeAttributes:
      containerName: containertest
      protocol: fuse
      resourceGroup: rg
      secretName: azure-secret
      storageAccount: bpstracc
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - '-o allow_other'
    - '--block-cache'
  volumeMode: Filesystem
