apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-failure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness
  template:
    metadata:
      labels:
        app: liveness
    spec:
      containers:
      - name: liveness
        image: registry.k8s.io/e2e-test-images/agnhost:2.40
        args:
        - liveness
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3