apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: test
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh", "-ec", "sleep 1000"]
      resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"