apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-dynamic
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-azurefile-dynamic
