kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-azurefile-dynamic
allowVolumeExpansion: true
mountOptions:
- mfsymlinks
- actimeo=30
parameters:
  skuName: Premium_LRS
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
