apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-cpu
  template:
    metadata:
      labels:
        app: stress-cpu
    spec:
      containers:
      - name: stress
        image: ubuntu
        command: ["/bin/bash"]
        args: ["-c", "apt-get update; apt-get install stress -y;stress --cpu 15"]