apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-mem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-mem
  template:
    metadata:
      labels:
        app: stress-mem
    spec:
      containers:
      - name: stress
        image: ubuntu
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["/bin/bash"]
        args: ["-c", "apt-get update; apt-get install stress -y;stress --vm 1 --vm-bytes 250M --vm-hang 1"]