apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-helloworld
  namespace: {{ .Values.namespace }}
  annotations:
    {{ .Values.rewrite }}: {{ .Values.rewriteTarget }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - http:
      paths:
      - path: /helloworld
        pathType: Exact
        backend:
          service:
            name: aks-helloworld-frontend
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnetapp
  namespace: {{ .Values.namespace }}
  annotations:
    {{ .Values.rewrite }}: {{ .Values.rewriteTarget }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - http:
      paths:
      - path: /aspnetapp
        pathType: Exact
        backend:
          service:
            name: aspnetapp
            port:
              number: 80