apiVersion: apps/v1
kind: Deployment
metadata:
  name: antiaffinity
spec:
  replicas: 2
  selector:
    matchLabels:
      component: am
  template:
    metadata:
      labels:
        component: am
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 128Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - am
              topologyKey: kubernetes.io/hostname
            weight: 100