apiVersion: apps/v1
kind: Deployment
metadata:
  name: requiredantiaffinity
spec:
  replicas: 2
  selector:
    matchLabels:
      component: am
  template:
    metadata:
      labels:
        component: am
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 128Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - am
            topologyKey: kubernetes.io/hostname