apiVersion: v1
kind: Pod
metadata:
  name: run-as-user
spec:
  securityContext:
    runAsUser: 1000
  volumes:
  - name: run-as-user
    emptyDir: {}
  containers:
  - name: run-as-user
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: run-as-user
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false