apiVersion: v1
kind: Pod
metadata:
  name: run-as-user
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: run-as-user
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: run-as-user
      mountPath: /data/demo
    - name: azure
      mountPath: /mnt/azure
    securityContext:
      allowPrivilegeEscalation: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 256Mi
  volumes:
  - name: run-as-user
    emptyDir: {}
  - name: azure
    csi: 
      driver: file.csi.azure.com
      readOnly: false
      volumeAttributes:
        secretName: azure-secret  # required
        shareName: test  # required  