apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-cpu
  namespace: stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-cpu
  template:
    metadata:
      labels:
        app: stress-cpu
    spec:
      containers:
      - name: stress
        image: ubuntu
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
        command: ["/bin/bash"]
        args: ["-c", "apt-get update; apt-get install stress -y;stress --cpu 15"]