apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob-static
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    volumeHandle: {{ .Values.resourceGroupName }}{{ .Values.storageAccountName }}{{ .Values.containerName }}
    volumeAttributes:
      resourceGroup: {{ .Values.resourceGroupName }}
      storageAccount: {{ .Values.storageAccountName }}
      containerName: {{ .Values.containerName }}
      # Identity can be used instead of secret
      #AzureStorageAuthType: msi  # key, sas, msi, spn
      #azureStorageIdentityClientID: {{ .Values.kubeletClientId }}
    nodeStageSecretRef:
      name: azure-blob-secret
      namespace: {{ .Values.namespace }}