apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob-static
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob-static
  storageClassName: azureblob-fuse-premium