apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-frontend
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-helloworld
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
  namespace: default
spec:
  selector:
    app: aspnetapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080