apiVersion: v1
kind: Pod
metadata:
  name: run-as-user
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: run-as-user
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: run-as-user
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 256Mi
  volumes:
  - name: run-as-user
    emptyDir: {}